### ISSUE TITLE
Framework does not contain slices for simulator architecture

### ISSUE THREAD

**Issue by mgrebenets** [bluecats/bluecats-ios-sdk-rc#2]
The static library binary inside the framework folder contains only `armv7` and `arm64` architecture slices.

This makes it impossible to build for simulator.
Which means no debugging, no unit testing and so on.

The `libBlueCatsSDK.a` library, contains all 5 required slices.

**Comment by zachabc24** [comment]
As far as I know, the App Store still does not allow frameworks built for the simulator. So our users would be required to strip the x86_64/i386 architectures from the FAT binary before submitting. We are considering adding another Framework option to the repo that includes simulator architecture for development. Would that help? Are other options we should consider?

**Comment by mgrebenets** [comment]
Interesting. Is there any link to discussion/documentation with regards to this limitation?

As a matter of fact, we've just submitted an app to App Store just recently, which uses `SplunkMint` static framework. `SplunkMint` framework includes simulator slices as well. This is 2nd submission, so we have a version live in App Store.

Technically, static framework is just a static library packaged in a folder and named a bit different.

Maybe that limitation applies to _dynamic_ frameworks? 

`BlueCatsSDK` is still a static framework though.

**Comment by zachabc24** [comment]
What does your PodFile look like? Here is the output after running 'file BlueCatsSDK' on my machine.

file BlueCatsSDK 
BlueCatsSDK: Mach-O universal binary with 2 architectures
BlueCatsSDK (for architecture armv7):	Mach-O dynamically linked shared library arm
BlueCatsSDK (for architecture arm64):	Mach-O 64-bit dynamically linked shared library

and here is using the static lib:

file libBlueCatsSDK.a 
libBlueCatsSDK.a: Mach-O universal binary with 5 architectures
libBlueCatsSDK.a (for architecture armv7):	current ar archive random library
libBlueCatsSDK.a (for architecture armv7s):	current ar archive random library
libBlueCatsSDK.a (for architecture i386):	current ar archive random library
libBlueCatsSDK.a (for architecture x86_64):	current ar archive random library
libBlueCatsSDK.a (for architecture arm64):	current ar archive random library

**Comment by mgrebenets** [comment]
You are right, I missed the fact that those slices are dynamically linked.

Do you plan to offer a solution for framework users?
It is extremely inconvenient to be limited to device-only testing when using blue cats sdk framework.

Would you consider doing the same thing Realm did with their framework?
They use `lipo` to put all the slices into one dynamic framework, so developers can use simulator and device. Then they strip simulator slices from their framework when the app is being archived.

Even if the stripping is not automatic, we, framework users, can use a script like Realm's one and strip the simulator slices before app submission.

The point here is that we can easily strip unwanted stuff, but we can't inject missing slices ourself, because we simply don't have them.

Here's the SO discussion on the matter: http://stackoverflow.com/questions/29634466/how-to-export-fat-cocoa-touch-framework-for-simulator-and-device
The accepted answer has all the links to Realm scripts:
https://github.com/realm/realm-cocoa/blob/master/scripts/strip-frameworks.sh

**Comment by damoclarke** [comment]
Hi @mgrebenets. We have decided to exclude simulator slices from the dynamic framework for the immediate release as we want to make sure we manage having multiple versions of the framework to avoid confusion. We will consider adding a version of the dynamic framework as a separate pod in a later release. In the meantime you should be able to use the static lib if you need to build for simulator. Let us know if you have any problems with that. Thanks.
