### ISSUE TITLE
Static framework is copied into a project as a resource

### ISSUE THREAD

**Issue by mgrebenets** [bluecats/bluecats-ios-sdk-rc#3]
The podspec for `0.7.2` version contains following:

```ruby
s.resource = 'BlueCatsSDK.framework'
```

This is actually wrong. This way the BlueCatsSDK.framework is copied into main app target _as a resource_ and in the end the app won't install on real device. Xcode complains about the BlueCatsSDK.framework being incorrectly signed.

**Comment by zachabc24** [comment]
Thanks, I am looking into this.

**Comment by damoclarke** [comment]
Thanks. We have amended the podspec in ba4257c7e2c43de69791bbf15bec1a20500bb046
