### ISSUE TITLE
Missing bitcode support

### ISSUE THREAD

**Issue by mgrebenets** [bluecats/bluecats-ios-sdk-rc#4]
When building project with bitcode enabled the build fails.
The reason is that blue cats sdk framework was not build with bitcode support.

This is a huge blocker, it forces framework users to opt out of bitcode support and as a result to opt out of App thinning.

**Comment by mgrebenets** [comment]
I guess this is related to #2 
We have packed static library as static framework, because we didn't have simulator slices.
But the static library was not built with Bitcode support it seems.

It is still possible though to build static library (and framework) with bitcode support.
The SplunkMint static framework which we use has the bitcode support.
I've just checked it like so:

```
otool -arch arm64 -l ./Pods/SplunkMint/SplunkMint.framework/SplunkMint  | grep bitcode
```

**Comment by damoclarke** [comment]
Hi. Both framework and static lib have bitcode support in latest release (rc3)
