### ISSUE TITLE
Add one more podspec for static framework

### ISSUE THREAD

**Issue by mgrebenets** [bluecats/bluecats-ios-sdk-rc#5]
Hi guys, this is related to #2 and #4 

Would you consider adding one more podspec for static framework?

Until dynamic framework has simulator slices it it, we can't really use it. The impact on development is too high due to the fact that we can't debug and test the app in simulator.

As a workaround, you could create one more podspec for Static Framework.
This is essentially a static `libBlueCatsSDK.a` library, only packed up in the `.framework` library along with the headers.

The reason for this request is because we can't use `libBlueCatsSDK.podspec` with `Podfile` which uses `use_frameworks!`. CocoaPods doesn't support adding static libraries in such a way. But it still works if static library is wrapped up in static framework.

**Comment by mgrebenets** [comment]
[StaticFramework.zip](https://github.com/bluecats/bluecats-ios-sdk-rc/files/375001/StaticFramework.zip)

Here's the static framework we came up with ourselves along with patched podspec.
If it helps.

If this static framework would also have bitcode support in it, it would be super.

**Comment by damoclarke** [comment]
hi @mgrebenets. Thanks for all of your feedback. We have been testing internally and believe we can support most of your requests, but we are reviewing the best way to manage the different framework and library options and their corresponding podspecs. We are planning a final release candidate for early next week and will look to include a number of these changes, so will let you know when they're ready for you to try out. Thanks.

**Comment by damoclarke** [comment]
hi @mgrebenets. I have pushed a new release candidate which from my testing allows you to use the static library in a project with `use_frameworks!`. Let me know if you have any problems with that.

Both the framework and the static library are now compiled with bitcode support.

**Comment by mgrebenets** [comment]
Have you guys tried to import `BlueCatsSDK` module in Swift code while using `libBlueCatsSDK` podspec?

I can't make it working.
Doesn't help even if I add `#import <BlueCatsSDK.h>` or `#import <libBlueCatsSDK/BlueCatsSDK.h>` in the bridging header.

I can't be 100% sure, but I'm afraid that when included as a static library, the `libBlueCatsSDK` pod will _not_ define a module, and that means it will not be available via Swift `import BlueCatsSDK` or even `import libBlueCatsSDK` statement.

That's why I suggested to wrap it into a static framework.
When added as a library, it's plugged in a via `-l"BlueCatsSDK"` compiler flag. When added as a static framework, it will be plugged in via `-framework "BlueCatsSDK"`, which will make it available as a module to all Swift code too.

**Comment by damoclarke** [comment]
Hi @mgrebenets. That's correct, the library won't be available as a swift module. It will need to be added to a bridging header (with `#import "BlueCatsSDK.h"` or `#import <libBlueCatsSDK/BlueCatsSDK.h>`) and then the module import `import BlueCatsSDK` won't be required as the library will already be available from the bridging header import.

Is adding the bridging header a problem for you or is it still not working even with the bridging header?

**Comment by damoclarke** [comment]
Just re-read your earlier comment that you had tried the bridging header already. One thing to note is that the `import BlueCats` in your application files is not required once you have the bridging header (I get a no such module BlueCatsSDK error if I try) and you should be able to use BlueCatsSDK classes within your project i.e. `BlueCatsSDK.startPurring()` etc.

**Comment by mgrebenets** [comment]
Hi @damoclarke 
Thanks for clarification!
It does work without imports indeed.

Since we had to jump from `0.7.2` to `2.0.0` am I understanding it correctly and `BCBeacon`'s `customValues` is now replaced with `customValueForKey`?

**Comment by zachabc24** [comment]
yes that's true @mgrebenets, customValues is now an NSDictionary called customValueForKey.
