### ISSUE TITLE
Missing gemfile

### ISSUE THREAD

**Issue by mgrebenets** [bluecats/bluecats-ios-sdk-rc#6]
Hi guys.

I'm pretty sure I've opened same issue in your other repo.
When I'm trying to lint your podspecs with CocoaPods v `1.0.0` it fails.
The reason seems to be that your podspecs are tailored for `0.39.0`.

We have to lint the spec, because we maintain a mirror of this github repo. So in the podspec we change github URL to our internal URL and then lint.

To make it easier, could you please add a `Gemfile` with specific CocoaPods version in it?

```ruby
# Gemfile
source "http://rubygems.org"
gem "cocoapods", "0.39.0"
```

`0.39.0` worked for me.

**Comment by damoclarke** [comment]
Addressed in related issue https://github.com/bluecats/bluecats-ios-sdk/issues/9
